### 1. Import numpy as np and see the version


In [6]:
import numpy as np
print(np.__version__)

1.24.3


### 2. How to create a 1D array?

Q. Create a 1D array of numbers from 0 to 9



In [7]:
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


### 3. How to create a boolean array?
Q. Create a 3×3 numpy array of all True’s


In [8]:
true_arr = np.full( (3,3), True)
print(true_arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### 4. How to extract items that satisfy a given condition from 1D array?
Q. Extract all odd numbers from arr



In [11]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

odd_arr = np.extract( (arr % 2 == 1), arr)
print(odd_arr)

[1 3 5 7 9]


### 5. How to replace items that satisfy a condition with another value in numpy array?
Q. Replace all odd numbers in arr with -1



In [18]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

odd_neg_arr = np.copyto(arr, -1, where= arr % 2 == 1)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### 6. How to replace items that satisfy a condition without affecting the original array?
Q. Replace all odd numbers in arr with -1 without changing arr

In [21]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

new_arr = np.where(arr % 2 == 1, -1, arr)

print('Orignal Array --> ', arr , '\n')
print('New Array --> ', new_arr)


Orignal Array -->  [0 1 2 3 4 5 6 7 8 9] 

New Array -->  [ 0 -1  2 -1  4 -1  6 -1  8 -1]


### 7. How to reshape an array?
Q. Convert a 1D array to a 2D array with 2 rows

In [26]:
arr = np.arange(10)

two_dim_arr = arr.reshape(2,-1)  # Setting to -1 automatically decides the number of cols
print(two_dim_arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### 8. How to stack two arrays vertically?
Q. Stack arrays a and b vertically

In [28]:
a = np.arange(6).reshape(2, -1)
b = np.repeat(3, 6).reshape(2, -1)

stacked_arr = np.vstack([a, b])
print(stacked_arr)

[[0 1 2]
 [3 4 5]
 [3 3 3]
 [3 3 3]]


### 9. How to stack two arrays horizontally?
Q. Stack the arrays a and b horizontally.

In [29]:
a = np.arange(6).reshape(2, -1)
b = np.repeat(3, 6).reshape(2, -1)

horizontal_arr = np.hstack([a,b])
print(horizontal_arr)

[[0 1 2 3 3 3]
 [3 4 5 3 3 3]]
