# NumPY Learning Started ( 30 July - 2023 )

## All Functions 
- arange( )
- zeros( )
- ones( )

In [1]:
import numpy as np

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr_zeros = np.zeros(3)
arr_zeros

array([0., 0., 0.])

In [6]:
arr_ones = np.ones(3)
arr_ones

array([1., 1., 1.])

# Random Module
- rand( )  -  random numbers b/w 0
- randn( )  -  random ( + & - ) numbers around 0
- randf( )   -  random float number b/w 0-1
- randint( )  -   random int b/w two points

In [10]:
rand = np.random.rand(5)
rand

array([0.11871951, 0.94875515, 0.09527668, 0.50767621, 0.68059863])

In [11]:
randn = np.random.randn(5)
randn

array([ 0.61633152, -0.5008657 ,  0.5326775 ,  0.92195412, -0.59143381])

In [13]:
ranf = np.random.ranf(5)
ranf

array([0.27762641, 0.16639741, 0.74708035, 0.4726393 , 0.7166261 ])

In [15]:
randint = np.random.randint(1,5,5)
randint

array([4, 3, 2, 3, 2])

## Data Type

- .dtype ( attribute ) can tell the Data Type of an array
- you can also change the data type , like converting floats to integers
- or you can change datatype by functions method np.float( arr ) or np.int_( arr )

In [19]:
x = [1.0, 6.7, 9.8]
xlist = np.array(x, dtype = "int32")

print(xlist, "Data Type " , xlist.dtype)

[1 6 9] Data Type  int32


## Arithmatic Operations

- np.add(a, b)
- np.subtract()
- np.multiply()
- np.divide()
- np.mod()
- np.power()
- np.reciprocal()

In [23]:
arr1 = [1,2,3,4]
arr2 = [3,2,6,9]

add_arr = np.add(arr1, arr2)
mult_arr = np.multiply(arr1, arr2)

print(add_arr)
print(mult_arr)


[ 4  4  9 13]
[ 3  4 18 36]


## Arithmatic Functions

- np.min()
- np.max()
- np.argmin() & np.argmax()  ,,,  Returns the index number of Min , Max - it can also be used inside as np.min(arr1, argmin(arr1) )
- np.sqrt()
- np.sin()
- np.cos()
- np.cumsum()   ,,, cumulative sum - summation of a sequence of numbers


In [29]:
arr = np.array( [ [3,4,5,7], [2,4,7,9] ] )

maximum_cols_element = np.max(arr, axis= 0)    # axis = 0   -  for searching in Columns
maximum_rows_element = np.max(arr, axis= 1)    # axis = 1   -  for searching in Rows
 
print(maximum_cols_element)
print(maximum_rows_element)

[3 4 7 9]
[7 9]


In [25]:
arr1 = np.array([7,2,4])

np.argmin(arr1)

1

In [30]:
arr = [1,2,6,4]

np.cumsum(arr)

array([ 1,  3,  9, 13])

## Shape & Reshape

In [32]:
arr = np.array([ [3,2,6], [3,5,8] ])

arr.shape

(2, 3)

In [34]:
arr = np.array( [1,6,7,3,6,2] )
new_arr = arr.reshape(2,3)

new_arr

array([[1, 6, 7],
       [3, 6, 2]])

In [36]:
# converts n dimensional array to 1 dimension

row_arr = new_arr.reshape(-1)   # Simply pass ( -1 )
row_arr

array([1, 6, 7, 3, 6, 2])

## Broadcasting Rule